Repository SEP-2019/Project-Athena, pull requests merged in 2019-03, with the labels that each got.

#66 Added Unit Test & Small fix
  backend/logic/courses/courses.js
  backend/logic/users/users.js
  backend/package-lock.json
  backend/routes/users.js
  backend/test/course_test.js
  backend/test/users_test.js
  backend/validation/format.js
Labels: backend

#72 Added course description and credits to db
  backend/logic/courses/courses.js
  backend/logic/users/users.js
Labels: backend, database

#71 Feras/backend/get student data
  backend/logic/courses/courses.js
  backend/logic/users/users.js
  backend/routes/courses.js
  backend/routes/users.js
  backend/test/course_test.js
  backend/test/users_test.js
  backend/validation/format.js
  db/update scripts/1.04.sql
Labels: backend, database, feature

#81 Signup Form Changes
  client/src/components/DropDownOutlined/DropDown.js
  client/src/components/DropDownOutlined/index.js
  client/src/components/EditText/EditText.js
  client/src/components/LoginForm/LoginForm.css
  client/src/components/LoginForm/SignupContent.jsx
  client/src/screens/Login/Login.css
  client/src/screens/Login/Login.js
Labels: FrontEnd

#86 prevent selecting same course in Course Registration page
  client/src/screens/CourseRegistration/CourseRegistration.js
Labels: FrontEnd

#80 clear checkboxes when press 'Clear All'
  client/src/components/ComplementaryPanel/ComplementaryPanel.js
Labels: FrontEnd, enhancement, feature

#83 Tyrone/backend/db/add course details
  .gitignore
  backend/package-lock.json
  backend/sql/curriculum_scripts/scrape_curriculum.js
Labels: backend, database, enhancement, feature

#89 Patrick/feature/connect curriculum endpoint
  .gitignore
  backend/logic/curriculums/curriculums.js
  backend/routes/curriculums.js
  client/package-lock.json
  client/package.json
  client/src/components/CourseTable/CourseTable.js
  client/src/components/ExpandableCourse/ExpandableCourse.js
  client/src/screens/CurriculumDisplay/CurriculumDisplay.css
  client/src/screens/CurriculumDisplay/CurriculumDisplay.js
Labels: FrontEnd

#84 Modified user/login endpoint, now it returns studentID on authenticated
  backend/logic/users/users.js
  backend/routes/users.js
Labels: FrontEnd, High Priority, backend

#91 Yueh/frontend/refactor code
  backend/app.js
  client/src/App.js
  client/src/components/ComplementaryPanel/ComplementaryPanel.js
  client/src/components/CompleteCourseList/CompleteCourseList.js
  client/src/components/CourseCheckBox/CourseCheckBox.js
  client/src/components/CourseSuggestionList/CourseSuggestionList.js
  client/src/components/CourseTable/CourseTable.js
  client/src/components/ExpandableCourse/ExpandableCourse.js
  client/src/components/MandatoryPanel/MandatoryPanel.js
  client/src/components/MuiStyle/commonStyle.js
  client/src/components/TagCheckBox/TagCheckBox.js
  client/src/components/TagList/TagList.js
Labels: FrontEnd

#95 Tyrone/sign in/test
  backend/test/users_test.js
Labels: backend

#97 Added title and course desc to getStudentData
  backend/logic/users/users.js
Labels: backend, database

#96 Fixed validation error thing and inserted email in header and left dr…
  client/package-lock.json
  client/src/App.js
  client/src/components/HeaderBar/HeaderBar.js
  client/src/components/LeftDrawer/LeftDrawer.js
  client/src/components/LoginForm/LoginContent.jsx
  client/src/components/LoginForm/LoginForm.jsx
  client/src/hocs/WithHeaderBar/WithHeaderBar.jsx
  client/src/index.js
  client/src/screens/Login/Login.js
Labels: FrontEnd

#98 GET requests for courses and semesters
  client/src/screens/CourseRegistration/CourseRegistration.js
Labels: FrontEnd

#90 Login functionality
  backend/package-lock.json
  client/src/App.js
  client/src/components/DropDownOutlined/DropDown.js
  client/src/components/EditText/EditText.js
  client/src/components/HeaderBar/HeaderBar.js
  client/src/components/LeftDrawer/LeftDrawer.js
  client/src/components/LoginForm/LoginContent.jsx
  client/src/components/LoginForm/LoginForm.css
  client/src/components/LoginForm/LoginForm.jsx
  client/src/components/LoginForm/SignupContent.jsx
  client/src/components/LoginForm/Validation.js
  client/src/hocs/WithHeaderBar/WithHeaderBar.jsx
  client/src/index.js
  client/src/screens/CurriculumDisplay/CurriculumDisplay.js
  client/src/screens/Login/Login.js
Labels: FrontEnd

#114 Did everything in Course Registration page 🙆🏻‍♀️
  backend/logic/courses/courses.js
  client/src/components/Loading/Loading.css
  client/src/components/Loading/Loading.js
  client/src/components/Loading/index.js
  client/src/components/SearchBar/SearchBar.css
  client/src/components/SearchBar/SearchBar.js
  client/src/screens/CourseRegistration/CourseRegistration.css
  client/src/screens/CourseRegistration/CourseRegistration.js
Labels: FrontEnd, High Priority, backend

#115 Feras/frontend/logout
  client/src/App.js
  client/src/components/LeftDrawer/LeftDrawer.js
  client/src/components/LoginForm/LoginContent.jsx
  client/src/hocs/WithHeaderBar/WithHeaderBar.jsx
  client/src/screens/CourseRegistration/CourseRegistration.js
  client/src/screens/CourseSuggestion/CourseSuggestion.js
  client/src/screens/CurriculumDisplay/CurriculumDisplay.js
Labels: FrontEnd, feature

#122 fix searchBar selection 🔧
  client/src/components/SearchBar/SearchBar.css
  client/src/components/SearchBar/SearchBar.js
  client/src/screens/CourseRegistration/CourseRegistration.js
Labels: FrontEnd

#126 passes empty value on clear input for searchBar ✈️
  client/src/components/SearchBar/SearchBar.js
  client/src/screens/CourseRegistration/CourseRegistration.js
Labels: FrontEnd

#133 Removed all the console.log 🙅🏻‍♀️
  client/src/components/HeaderBar/HeaderBar.css
  client/src/components/HeaderBar/HeaderBar.js
  client/src/hocs/WithHeaderBar/WithHeaderBar.jsx
  client/src/screens/CourseRegistration/CourseRegistration.js
  client/src/screens/CourseSuggestion/CourseSuggestion.js
  client/src/screens/CurriculumDisplay/CurriculumDisplay.css
  client/src/screens/CurriculumDisplay/CurriculumDisplay.js
Labels: FrontEnd

#136 🔥💖✨🌸made nice favicon 🌸✨💖🔥
  client/public/favicon.ico
Labels: FrontEnd
